### ISSUE TITLE
Document core vs. extended API commands

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.py#118]
PyOTA defines 2 classes of API commands:  core and extended.

- `core` commands are exposed directly by the [IRI API](https://iota.readme.io/reference).  PyOTA installs a thin layer in front so that it can validate inputs, but otherwise it does little more than pass the inputs to the IRI and return the resulting outputs.  The `StrictIota` class acts as the interface for core commands.
- `extended` commands extend the core API by performing offline operations, chaining multiple API calls together, etc.  The `Iota` class acts as the interface for extended commands.  `Iota` derives from `StrictIota`, so it can also call any of the core commands (making it a good choice for most applications).

PyOTA follows the pattern that [python-redis](https://pypi.python.org/pypi/redis/#api-reference) uses.  The `StrictRedis` class exposes only the commands supported by the Redis API, while the `Redis` class contains additional commands that extend the core API (in this case, to provide backwards compatibility).

The problem is, none of this appears in the PyOTA documentation, so users and contributors are left scratching their heads about which class to use, wheer to put new commands, etc.

Please update the PyOTA documentation with more info about the differences between core and extended commands, and `StrictIota` vs. `Iota`.

**Comment by lzpap** [comment]
Solved by #261
