### ISSUE TITLE
TryteString.random() should use cls.LEN as its default length, when available

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.py#166]
When calling a class' `random()` method, the `length` parameter should only be required if the class has no `LEN` attribute.

Example:

```python
>>> from iota import Address
>>> Address.random()

# Expected Result
Address(b'... 81 random trytes ...')

# Actual Result
TypeError: random() missing 1 required positional argument: 'length'
```

**Comment by redondo-mk** [comment]
Does this mean that every class that is a subclass of `TryteString` and has `LEN` class attribute needs to override `random` class method:
```
    @classmethod
    def random(cls, length=LEN):
        return super(Address, cls).random(length)
```
Is more elegant solution possible - changes only in the `TryteString` class?

**Comment by todofixthis** [comment]
Hey @redondo-mk it should automatically use `cls.LEN` when `length` is `None`; see https://github.com/iotaledger/iota.lib.py/pull/167/files#diff-d6aa393b4abd731eaf02e44ac1dc7d5aR64

**Comment by xie4991** [comment]
You can try this：Address.random().choice(81 random trytes )
It may be solved by giving a limited range later.
