### ISSUE TITLE
PyOTA with MicroPython

### ISSUE THREAD

**Issue by huggre** [iotaledger/iota.py#266]
Hi, would it be possibly to run PyOTA with MicroPython on lets say, an ESP32 micro-controller?
If not, what would it take to create a version (like a MicroPyOTA) that would?
- Not possible
- Total re-write
- Minor adjustments
- Etc.

Thanks for all your great work on this excellent library, nice to see PyOTA come to life again :-)

**Comment by lzpap** [comment]
Hi @huggre, thanks for your question!
In short, I would say that PyOTA would need some serious modifications to be able to run with MicroPython. I'm no expert on MicroPython, but I'll try to summarize what I concluded after a quick look:
 - PyOTA uses a number of standard libraries from CPython, that might or might not be ported to MicroPython yet. I see that for example `requests` has been ported to `urequests`, but `deque` has no alternative.
 - There are external library dependencies (see `setup.py`) in PyOTA like `pysha3`, `filters` or `six` that might not be compatible with MicroPython.
- Metaclasses are not supported in MicroPython, however, they are utilized in PyOTA.
- A serious issue might be unicode string handling and byte encoding. [This](https://docs.micropython.org/en/latest/genrst/builtin_types.html#bytes-with-keywords-not-implemented) could make `TryteString` encoding and decoding quite challenging.

These are my quick thoughts, probably there are more problems that will pop up as you start porting. The cleanest solution might be to rewrite the library, however, I think you can make it work if you figure out the problems listed above.

On the other hand, IOTA has a C library that is demonstrated to work with ESP32 microcontrollers, [check out this blog post from Sam Chen](https://blog.iota.org/running-the-iota-cclient-library-on-esp32-4a1a5191afad).

I hope I could help! :-)

**Comment by huggre** [comment]
Thanks for your feedback @lzpap, this is very useful info. for me. 
Porting PyOTA to MicroPython is unfortunately way beyond what i would be able to do with my limited Python experience. Guess i just have to wait and see if anyone picks up the challenge in the future :-)
Until then the C library is for sure an option (or simply use a smaller Raspberry board such as the Zero)
