### ISSUE TITLE
Fix typo in docs parameter description

### ISSUE THREAD

**Issue by m3rlin5ky** [iotaledger/iota.py#330]
## **Description of change**

Fix a typo in the parameter description on page 47 at bulletpoint devnet (2nd row)
->> The MWM of the mainnet should be 14 and not 1.

## **Type of change**

Documentation Fix

## **Image of the typo**

![image](https://user-images.githubusercontent.com/43293035/80616136-cf60f780-8a40-11ea-90a6-96c980aac088.png)

**Comment by anistark** [comment]
@todofixthis Can I take this up? Good first issue to get started with.
